version: "2.1"

networks:
  monitor-net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.18.1
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  alertmanager:
    image: prom/alertmanager:v0.20.0
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: prom/pushgateway:v1.2.0
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:7.0.0
    extra_hosts:
      # Set the BPTS Remote write target
      - "influxdb.robolab.innopolis.ru:188.130.155.105"
    environment:
      GF_SECURITY_ADMIN_USER: ${ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "true"
      GF_RENDERING_SERVER_URL: http://grafana_remote_render:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      REMOTE_INFLUXDB_USER: ${REMOTE_INFLUXDB_USER}
      REMOTE_INFLUXDB_DB: ${REMOTE_INFLUXDB_DB}
      REMOTE_INFLUXDB_USER_PASSWORD: ${REMOTE_INFLUXDB_USER_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana_remote_render:
    image: grafana/grafana-image-renderer:latest
    networks:
      - monitor-net
    environment:
      ENABLE_METRICS: "true"
    labels:
      org.label-schema.group: "monitoring"

  caddy:
    image: stefanprodan/caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
      - "8083:8086"
    volumes:
      - ./caddy:/etc/caddy
      - ./ssl:/etc/caddy/ssl
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v0.18.1
    pid: "host"
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    privileged: yes
    pid: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.16.0
    restart: unless-stopped
    expose:
      - 9115
    networks:
      - monitor-net
    volumes:
      - ./blackbox_exporter/config.yml:/etc/blackbox_exporter/config.yml
    labels:
      org.label-schema.group: "monitoring"

  snmp-exporter:
    image: prom/snmp-exporter:v0.18.0
    restart: unless-stopped
    expose:
      - 9116
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  script-exporter:
    build: script_exporter/
    restart: unless-stopped
    expose:
      - 9172
    networks:
      - monitor-net
    volumes:
      - ./script_exporter:/etc/script-exporter:ro
      - /dev:/dev:ro
    labels:
      org.label-schema.group: "monitoring"
