version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.6.4
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=172.17.0.1:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - ROOT_URL=https://cordelianew.university.innopolis.ru/gitea
    restart: always
    networks:
      - gitea
    volumes:
      - /srv/gitea:/data
    ports:
      - "3000:3000