{
 "title": "Alerts - Windows Nodes",
 "description": "Alerts for Windows Nodes using prometheus and wmi_exporter. You can have alerts for Disk space, CPU and Memory. Also added a log of alerts and alert status.",
 "tags": [
  "alerts",
  "windows"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Alerts Status", "type": "alertlist", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 } },
  { "title": "Alerts Log", "type": "alertlist", "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 } },
  {
   "title": "Windows Nodes Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * ((wmi_logical_disk_free_bytes{} / 1000 / 1000 ) / (wmi_logical_disk_size_bytes{}  / 1024 / 1024))",
     "legendFormat": "{{instance}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Windows Nodes CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(wmi_cpu_time_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Windows Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(wmi_os_physical_memory_free_bytes) / wmi_cs_physical_memory_bytes ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}