{
 "title": "Autonomous Car Central Management Panel",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   {
    "name": "car",
    "label": "Autonomous Car",
    "query": "SELECT car,\"value\" FROM \"up\" GROUP BY \"car\""
   }
  ]
 },
 "panels": [
  { "title": "General Inspection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Probes",
   "type": "table-old",
   "description": "Probes done over TCP/IP connection",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "targets": [
    { "expr": "probe_success" }
   ]
  },
  {
   "title": " Manual Script Execution Probes",
   "type": "table-old",
   "description": "Probes provided by Bash script executed",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 1 },
   "targets": [
    { "expr": "script_success" }
   ]
  },
  {
   "title": "Probes Issues - Historic",
   "type": "graph",
   "description": "Probes done over TCP/IP connection",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "1 - probe_success" },
    { "expr": "1 - script_success" }
   ]
  },
  { "title": "$car", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "car" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "node_time_seconds",
     "query": "SELECT \"value\" FROM \"node_time_seconds\",\"node_boot_time_seconds\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter FILL(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Component Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "description" ], "type": "tag" }
     ],
     "measurement": "probe_success",
     "query": "SELECT \"value\" FROM \"probe_success\",\"script_success\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"description\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Car Components Probes Availability Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "description" ], "type": "tag" }
     ],
     "measurement": "probe_success",
     "query": "SELECT last(\"value\") FROM \"probe_success\",\"script_success\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"description\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_cpu_seconds_total",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"node_cpu_seconds_total\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"mode\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Free Space - Overall View",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_filesystem_avail_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" },
      { "condition": "AND", "key": "fstype", "operator": "=", "value": "ext4" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_filesystem_size_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" },
      { "condition": "AND", "key": "fstype", "operator": "=", "value": "ext4" }
     ]
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_network_receive_bytes_total",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"node_cpu_seconds_total\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"mode\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_network_transmit_bytes_total",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"node_cpu_seconds_total\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"mode\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "RAM Total",
     "measurement": "node_memory_MemTotal_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "alias": "RAM Free",
     "measurement": "node_memory_MemFree_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "alias": "SWAP Total",
     "measurement": "node_memory_SwapTotal_bytes",
     "query": "SELECT \"value\" FROM \"node_memory_SwapTotal_bytes\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "alias": "SWAP Free",
     "measurement": "node_memory_SwapFree_bytes",
     "query": "SELECT \"value\" FROM \"node_memory_SwapTotal_bytes\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "nvidia_gpu_duty_cycle",
     "query": "SELECT value FROM nvidia_gpu_duty_cycle, nvidia_gpu_num_devices WHERE (\"car\" =~ /^$car$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  { "title": "$car", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "node_time_seconds",
     "query": "SELECT \"value\" FROM \"node_time_seconds\",\"node_boot_time_seconds\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter FILL(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Component Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "description" ], "type": "tag" }
     ],
     "measurement": "probe_success",
     "query": "SELECT \"value\" FROM \"probe_success\",\"script_success\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"description\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Car Components Probes Availability Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "description" ], "type": "tag" }
     ],
     "measurement": "probe_success",
     "query": "SELECT last(\"value\") FROM \"probe_success\",\"script_success\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"description\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_cpu_seconds_total",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"node_cpu_seconds_total\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"mode\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Free Space - Overall View",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_filesystem_avail_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" },
      { "condition": "AND", "key": "fstype", "operator": "=", "value": "ext4" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_filesystem_size_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" },
      { "condition": "AND", "key": "fstype", "operator": "=", "value": "ext4" }
     ]
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_network_receive_bytes_total",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"node_cpu_seconds_total\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"mode\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_network_transmit_bytes_total",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"node_cpu_seconds_total\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"mode\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "RAM Total",
     "measurement": "node_memory_MemTotal_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "alias": "RAM Free",
     "measurement": "node_memory_MemFree_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "alias": "SWAP Total",
     "measurement": "node_memory_SwapTotal_bytes",
     "query": "SELECT \"value\" FROM \"node_memory_SwapTotal_bytes\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "alias": "SWAP Free",
     "measurement": "node_memory_SwapFree_bytes",
     "query": "SELECT \"value\" FROM \"node_memory_SwapTotal_bytes\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "nvidia_gpu_duty_cycle",
     "query": "SELECT value FROM nvidia_gpu_duty_cycle, nvidia_gpu_num_devices WHERE (\"car\" =~ /^$car$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  { "title": "$car", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "node_time_seconds",
     "query": "SELECT \"value\" FROM \"node_time_seconds\",\"node_boot_time_seconds\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter FILL(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Component Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "description" ], "type": "tag" }
     ],
     "measurement": "probe_success",
     "query": "SELECT \"value\" FROM \"probe_success\",\"script_success\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"description\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Car Components Probes Availability Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "description" ], "type": "tag" }
     ],
     "measurement": "probe_success",
     "query": "SELECT last(\"value\") FROM \"probe_success\",\"script_success\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"description\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_cpu_seconds_total",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"node_cpu_seconds_total\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"mode\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Free Space - Overall View",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_filesystem_avail_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" },
      { "condition": "AND", "key": "fstype", "operator": "=", "value": "ext4" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_filesystem_size_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" },
      { "condition": "AND", "key": "fstype", "operator": "=", "value": "ext4" }
     ]
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_network_receive_bytes_total",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"node_cpu_seconds_total\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"mode\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "node_network_transmit_bytes_total",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"node_cpu_seconds_total\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter GROUP BY \"mode\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "RAM Total",
     "measurement": "node_memory_MemTotal_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "alias": "RAM Free",
     "measurement": "node_memory_MemFree_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "alias": "SWAP Total",
     "measurement": "node_memory_SwapTotal_bytes",
     "query": "SELECT \"value\" FROM \"node_memory_SwapTotal_bytes\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    },
    {
     "alias": "SWAP Free",
     "measurement": "node_memory_SwapFree_bytes",
     "query": "SELECT \"value\" FROM \"node_memory_SwapTotal_bytes\" WHERE (\"car\" =~ /^$car$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "nvidia_gpu_duty_cycle",
     "query": "SELECT value FROM nvidia_gpu_duty_cycle, nvidia_gpu_num_devices WHERE (\"car\" =~ /^$car$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "car", "operator": "=~", "value": "/^$car$/" }
     ]
    }
   ]
  }
 ]
}