{
 "title": "Blackbox Exporter Quick Overview",
 "description": "Quick overview of values from blackbox exporters",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "targets",
    "query": "label_values(probe_success, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bare Metal Server Probes (Up/Down) - Current",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_success" }
   ]
  },
  {
   "title": "Bare Metal Server Probes (Up/Down) - Historic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "- probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry-time()",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_dns_lookup_time_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}