{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "gpu_server",
    "label": "GPU Server",
    "query": "label_values(nvidia_gpu_num_devices, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Available Nvidia GPU",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nvidia_gpu_memory_total_bytes{instance=~\"$gpu_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_duty_cycle{instance=~\"$gpu_server\"}",
     "legendFormat": "{{instance}} - gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_memory_used_bytes{instance=~\"$gpu_server\"}",
     "legendFormat": "{{instance}} - gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_gpu_duty_cycle{instance=~\"$gpu_server\"}) / sum(nvidia_gpu_num_devices{instance=~\"$gpu_server\"})"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 5, "x": 3, "y": 7 } },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_gpu_memory_used_bytes{instance=~\"$gpu_server\"}) / sum(nvidia_gpu_num_devices{instance=~\"$gpu_server\"})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_temperature_celsius",
     "legendFormat": "{{instance}} - gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_fanspeed_percent{instance=~\"$gpu_server\"}",
     "legendFormat": "{{instance}} - gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "# GPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nvidia_gpu_num_devices{instance=~\"$gpu_server\"})"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_power_usage_milliwatts{instance=~\"$gpu_server\"}",
     "legendFormat": "{{instance}} - gpu{{minor_number}}"
    }
   ]
  }
 ]
}