{
 "title": "Storage I/O Statistics",
 "description": "This dashboards shows IOPS, I/O Latency, Average Request size and throughput. Alerts are configured for latency.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(node_uname_info, instance)"
   },
   {
    "name": "device",
    "label": "Devicename",
    "query": "label_values(node_disk_io_now{instance=~\"$hostname\"}, device)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "iops", "label": "Reads" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m]) ",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "iops", "label": "Reads" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m]) ",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m]) / rate(node_disk_reads_completed_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m]) * 1000000",
     "legendFormat": "{{instance}} - {{device}} "
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) * 1000000",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Read Troughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps", "label": "Reads" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m])) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Troughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "Bps", "label": "Reads" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m])) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Request Size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m]) / rate(node_disk_reads_completed_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m]) ",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Write Request Size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m]) / rate(node_disk_writes_completed_total{instance=~\"$hostname\", job=~\"$job\", device=~\"$device\"}[1m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  }
 ]
}