{
 "title": "Windows Server",
 "description": "Windows",
 "tags": [ "windows" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(wmi_system_system_up_time, instance)"
   },
   {
    "name": "cpumode",
    "label": "cpumode",
    "query": "label_values(wmi_cpu_time_total, mode)"
   }
  ]
 },
 "panels": [
  {
   "title": "HD - Free space",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "wmi_logical_disk_free_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}"
    }
   ]
  },
  {
   "title": "HD - Free space, %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (wmi_logical_disk_size_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"} - wmi_logical_disk_free_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}) / wmi_logical_disk_size_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"} * 100",
     "legendFormat": "Free {{volume}}"
    }
   ]
  },
  {
   "title": "C:\\ Free space, %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (wmi_logical_disk_size_bytes{instance=~\"$server.*\", volume=\"C:\"} - wmi_logical_disk_free_bytes{instance=~\"$server.*\", volume=\"C:\"}) / wmi_logical_disk_size_bytes{instance=~\"$server.*\", volume=\"C:\"} * 100"
    }
   ]
  },
  {
   "title": "C:\\ - Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_logical_disk_size_bytes{instance=~\"$server.*\", volume=\"C:\"} "
    }
   ]
  },
  {
   "title": "HD - Used Space",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "wmi_logical_disk_size_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"} - wmi_logical_disk_free_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}"
    }
   ]
  },
  {
   "title": "HD - Used space, %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(wmi_logical_disk_size_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"} - wmi_logical_disk_free_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}) / wmi_logical_disk_size_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"} * 100",
     "legendFormat": "used {{volume}}"
    }
   ]
  },
  {
   "title": "C:\\ - Used space, %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(wmi_logical_disk_size_bytes{instance=~\"$server.*\", volume=\"C:\"} - wmi_logical_disk_free_bytes{instance=~\"$server.*\", volume=\"C:\"}) / wmi_logical_disk_size_bytes{instance=~\"$server.*\", volume=\"C:\"} * 100"
    }
   ]
  },
  {
   "title": "HOST",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "CPU usage, %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(wmi_cpu_time_total{mode=\"idle\", instance=~\"$server.*\"}[1m])) * 100) > 0"
    }
   ]
  },
  {
   "title": "CPU Usage, %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(wmi_cpu_time_total{mode=\"idle\", instance=~\"$server.*\"}[1m])) * 100) > 0"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - wmi_system_system_up_time{instance=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$server\"} - wmi_os_physical_memory_free_bytes{instance=~\"$server\"}",
     "legendFormat": "Usado"
    },
    {
     "expr": "wmi_os_physical_memory_free_bytes{instance=~\"$server\"}",
     "legendFormat": "Livre"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "Free Memory, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 15 },
   "targets": [
    {
     "expr": "100 - (wmi_cs_physical_memory_bytes{instance=~\"$server.*\"} - wmi_os_physical_memory_free_bytes{instance=~\"$server.*\"}) / wmi_cs_physical_memory_bytes{instance=~\"$server.*\"} * 100"
    }
   ]
  },
  {
   "title": "Memory Free, %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(wmi_cs_physical_memory_bytes{instance=~\"$server.*\"} - wmi_os_physical_memory_free_bytes{instance=~\"$server.*\"}) / wmi_cs_physical_memory_bytes{instance=~\"$server.*\"} * 100"
    }
   ]
  },
  {
   "title": "Memory in use",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 17 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$server.*\"} - wmi_os_physical_memory_free_bytes{instance=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 19 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "wmi_os_physical_memory_free_bytes{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Network Interface",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(wmi_net_bytes_sent_total{instance=~\"$server.*\"}[$interval]) >0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(wmi_net_bytes_received_total{instance=~\"$server.*\"}[$interval]) <0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "  sum(irate(wmi_net_bytes_total{instance=~\"$server.*\"}[5m])) / sum(wmi_net_current_bandwidth{instance=~\"$server.*\"}/8) * 100"
    }
   ]
  }
 ]
}