version: "3"
services:
  freeipa:
    image: freeipa/freeipa-server
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/ipa-data:/data:Z
    tmpfs:
      - /run
      - /tmp
    hostname: ipa
    domainname: example.test
