modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4" # defaults to "ip6"
  http_post_2xx:
    prober: http
    http:
      method: POST
  ntripcaster_mountpoint:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ipv4"
      query_response:
        - send: "GET /INNOPOLIS HTTP/1.1"
        - send: "User-Agent: NTRIP curl"
        - send: "Accept: */*"
        - send: "Authorization: Basic c2FudGE6ZmVkb3I="
        - send: "Ntrip-Version: Ntrip/2.0"
        - expect: "ICY 200 OK"
  tcp_connect:
    prober: tcp
    tcp:
      preferred_ip_protocol: "ipv4"
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
        - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
        - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
        - send: "NICK prober"
        - send: "USER prober prober prober :prober"
        - expect: "PING :([^ ]+)"
          send: "PONG ${1}"
        - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip4"
